Add files via upload
Python OpenCV | cv2.imread() method Library: OpenCV-Python

OpenCV is an open-source library of python specially designed for computer vision problems. OpenCV-Python is the module of OpenCV used for reading images. cv2.imread() method loads an image from the specified file/path. This method returns an empty matrix if the image cannot be read (because of the missing file, improper permissions, unsupported or invalid format) and this error type shown:

OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-
_8k9tw8n\opencv\modules\highgui\src\window.cpp:404: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

OpenCV-Python library can be install via pip and conda;





 
Example #1: Use flag by default
#OpenCV-Python
# Display an image with cv2.imread() Method/Function

# import cv2, we already install with pip/conda import cv2 as c

#where c is a reference variable of cv2
#You can set the reference variable by own just easy to use


File_path = r'C:/Users/oral_vision/Desktop/python_code/OpenCV_image.png' #used of 'r' to read the the file in specific path

image = c.imread(File_path)
#passing the path in cv2.imread() method

# c.imshow() method used for display image cv2.imshow('Displayed-image', image)
#Passing two parameter in cv2.imshow(), the file name, as you can set by own #and and read file(image)

c.waitKey(0)



Output:


 
In the above example #1, first, we import the cv2 library as reference variable c; you can set the reference variable on its own, just easy to use to reduce the library word. The first thing needs to install the python-OpenCV library through the command line or with IDE. Copy the file location path and past it in quotes. On the right side, use a character r which means to read. c.imread(File_path) needs two parameters: file path and flag integer value. when you are using IDE such as pycharm or Spyder, use a method waitKey with parameter 0, show image in the screen.


cv2.IMREAD method has three main type of flags;





Example #2: Read an image in grayscale mode
#OpenCV-Python
# Display an image with cv2.imread() Method/Function

# import cv2, we already install with pip/conda import cv2 as c

#where c is a reference variable of cv2
#You can set the reference variable by own just easy to use


File_path = r'C:/Users/oral_vision/Desktop/python_code/OpenCV_image.png' #used of 'r' to read the the file in specific path

image = c.imread(File_path,0)
#passing the path in cv2.imread() method

# c.imshow() method used for display image cv2.imshow('Displayed-image', image)
#Passing two parameter in cv2.imshow(), the file name, as you can set by own #and and read file(image)

c.waitKey(0)
 

Output:








In the above example #2, firstly, we import the cv2 library as reference variable c; rest of the code you can use c instead of cv2. You can set the reference variable on its own, just easy to use to reduce the library word. Copy the file location path and past it in quotes. On the right side, use a character r which means to read.c.imread(File_path) needs two parameters: file path and a flag integer value. As differentiate from example #1, you set the flag value to 0; the method read the one channel of the file (gray image).


 
Nowadays, the bands/channels of images are increasing, i.e., spectral images having 5 or 6 bands. GIS live data applications use high-quality images. Therefore, the flag parameter of the cv2.imread() method was also upgraded day by day. The parm flag has a predefined integer value to read a specific type of image. Such as RGB, gray, Spectral, etc.


Table 1: Imgproc class called by flag parameters

Serial No.	
Description
1	IMREAD_LOAD_GDAL: Load an image from the specific path in spectral band
mode. For a spectral image, pass value 8 integer flag.
2	IMREAD_ANYCOLOR: Load an image from the specific path in any possible color
format. For a spectral image, pass value 4 integer flag.
3	IMREAD_REDUCED_COLOR_2/IMREAD_REDUCED_COLOR_4/IMREAD_
REDUCED_COLOR_8: Read RGB image reduce the image size by ½, ¼th, or ⅛th of the original size of the image concerning the field used.
IMREAD_REDUCED_COLOR_2 flag = 17, IMREAD_REDUCED_COLOR_4 flag =
33, IMREAD_REDUCED_COLOR_8 flag = 65
4	IMREAD_REDUCED_GRAYSCALE_2/IMREAD_REDUCED_GRAYSCALE_4
/IMREAD_REDUCED_GRAYSCALE_8: Read image of single-channel image (grayscale) reduce the image size by ½, ¼th, or ⅛th of the original size of the image concerning the field used. IMREAD_REDUCED_GRAYSCALE_2 flag = 16, IMREAD_REDUCED_GRAYSCALE_4 flag = 32,
IMREAD_REDUCED_GRAYSCALE_8 = 64
 
Summary 

By concluding this instructional exercise of different Python cases, we learned to utilize cv2 imread() strategy to perused an image into a Python Array, and also the way in which the image should be read. We became known that how to use Open CV library and what are the requirements of it.


References:
https://docs.opencv.org/3.4/d8/d6a/group imgcodecs   flags.html

https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

https://www.tutorialspoint.com/opencv/opencv_imread_xxx_flag.htm

https://java2blog.com/cv2-imread-python/

https://appdividend.com/2020/06/17/how-to-read-an-image-using-opencv-in-python/